#pragma once

#define SECRET_WIFI_SSID         "YOUR_WIFI_SSID"
#define SECRET_WIFI_PASSWORD     "YOUR_WIFI_PASSWORD"

#define SECRET_HA_TOKEN          "YOUR_HA_TOKEN"
#define SECRET_API_TOKEN         "YOUR_API_TOKEN"
#define SECRET_WHISPER_TOKEN     "YOUR_WHISPER_TOKEN"
#define SECRET_ELEVENLABS_KEY    "YOUR_ELEVENLABS_KEY"
